# Site Settings
title:               boxcar data
tagline:             A data engineering blog
description:
baseurl:            #"/Lagrange"
url:                "https://boxcardata.github.io"
github:
  url:               "https://github.com/boxcardata
author:
  name:              "Oliver"
  email:             "boxcardata@gmail.com"
#  twitter:           "paululele"
#  instagram:         "paululele"
  github:            "boxcardata"
#  facebook:          "Le.Paul.94"
#  linkedin:          "lenpaul"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
